layout_spectrum: 0.8634064
typography_spectrum: 0.4738617
color:
  saturation: 0.7800019
  lightness: 0.7854841
  brandStrength: 0.1967575
  rhythmicContrast: 0.7344045
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Stenager
