name: Stenager Transport
favicon: null
layout_spectrum: 0.69616
typography_spectrum: 0.47249
title: Stenager Transport
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000100'
    - '#776757'
    - '#293438'
    - '#9e9b94'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
