name: Stenager Transport
favicon: null
layout_spectrum: 0.69616
typography_spectrum: 0.47249
title: Stenager Transport
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74768218-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6e67'
    - '#90877e'
    - '#c5c5c5'
    - '#4d262b'
    - '#fcfefe'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
