name: Stenager Transport
favicon: null
layout_spectrum: 0.49505
typography_spectrum: 0.5339
navigation:
  - name: Om os
    id: 8274e858-02d7-4731-b2a1-d4c8e9c61487
    type: content
  - name: Godstransport
    id: cae1b2bb-3e08-4e9a-aec6-b0fb3b32081f
    type: content
  - name: Studenterkørsel
    id: 29dd2635-1752-4e8b-b4ca-faf3a193691a
    type: content
  - name: Kompostspredning
    id: 0f34355e-9616-49e5-96e3-50ac2ef146f6
    type: content
title: Stenager Transport
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74768218-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6e67'
    - '#90877e'
    - '#c5c5c5'
    - '#4d262b'
    - '#fcfefe'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
