name: Stenager Transport
favicon: null
layout_spectrum: 0.4513
typography_spectrum: 0.47249
title: Stenager Transport
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce4ef'
    - '#817263'
    - '#b29965'
    - '#45473a'
    - '#ae3a44'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.7344045
purpose: []
